version: '3'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "50m"
    max-file: "4"

services:
  proxy:
    image: nginx:1-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - lemmy-ui
    logging: *default-logging

  lemmy:
    image: dessalines/lemmy:0.19.3
    hostname: lemmy
    restart: always
    ports:
      - "8536:8536"
    environment:
      - RUST_LOG=warn
      - LEMMY_DATABASE_URL=postgres://lemmy:password@postgres:5432/lemmy
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      postgres:
        condition: service_healthy
      pictrs:
        condition: service_started
    logging: *default-logging

  lemmy-ui:
    image: dessalines/lemmy-ui:0.19.3
    restart: always
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST=localhost:8536
      - LEMMY_UI_HTTPS=false
    ports:
      - "1234:1234"
    depends_on:
      - lemmy
    logging: *default-logging

  pictrs:
    image: asonix/pictrs:0.4.0-rc.13
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PICTRS__MEDIA__VIDEO_CODEC=vp9
    volumes:
      - ./volumes/pictrs:/mnt
    logging: *default-logging

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=lemmy
      - POSTGRES_DB=lemmy
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "lemmy"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging: *default-logging


